version: 1.0.{build}
services: mssql2016
build:
  verbosity: minimal
after_test: 
  - .\packages\OpenCover.4.6.519\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\Arinna.Test\bin\Debug\Arinna.Test.dll" -filter:"+[Arinna]*  -[Arinna]Arinna.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\Arinna_coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "Arinna_coverage.xml"
